#--------------------------------------------
#
#
#
#--------------------------------------------

name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk

env:
  AWS_REGION                : "eu-central-1"
  EB_PACKAGE_S3_BACKET_NAME : "yura-flask-application-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB-ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKGE_NAME        : "flask_app_${{ github.sha }}.zip"

on:
  push:
    branches:
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKGE_NAME }} ./ -x *.git*
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy Deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKGE_NAME }} s://${{ env.EB_PACKAGE_S3_BACKET_NAME }}/



#  my_cd_part:
#    runs-on: ubuntu-latest
