#--------------------------------------------
#
#
#
#--------------------------------------------

name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk

env:
  AWS_REGION                : "eu_central_1"                   # set this to your preferred AWS region, e.g. us-west-1
  EB_PACKAGE_S3_BACKET_NAME : "S3"
  EB_APPLICATION_NAME       : "MyFlask"
  EB-ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKGE_NAME        : "flask_app_${{ gitnub.sha }}.zip"

on:
  push:
    branches:
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKGE_NAME }} ./ -x *.git*
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1



  my_cd_part:
    runs-on: ubuntu-latest


###
permissions:
  contents: read


